export default {
  isLoggedIn: false,
  assetIdCount: 6,
  assigneeIdCount: 2,
  action: "",
  asset: {},
  assets: [
    {
      asset_id: 1,
      name: "PC",
      description: "i3",
      type: "Machine",
      serial: "Machine-1",
      assignee: "John Doe",
      tracker_no: "ABC103-400400-1",
      status: "ACTIVE",
      location: [10, 10],
    },
    {
      asset_id: 2,
      name: "SUV",
      description: "Ertiga",
      type: "Vehicle",
      serial: "Vehicle-2",
      assignee: "Jane Doe",
      tracker_no: "ABC103-400400-2",
      status: "ACTIVE",
      location: [10, 10],
    },
    {
      asset_id: 3,
      name: "Table",
      description: "100x100x50",
      type: "Other",
      serial: "Other-3",
      assignee: "John Doe",
      tracker_no: "ABC103-400400-3",
      status: "ACTIVE",
      location: [10, 10],
    },
    {
      asset_id: 4,
      name: "Table",
      description: "120x120x50",
      type: "Other",
      serial: "Other-4",
      assignee: "Jane Doe",
      tracker_no: "ABC103-400400-4",
      status: "ACTIVE",
      location: [10, 10],
    },
    {
      asset_id: 5,
      name: "Sedan",
      description: "Mustang",
      type: "Vehicle",
      serial: "Vehicle-5",
      assignee: "John Doe",
      tracker_no: "ABC103-400400-5",
      status: "ACTIVE",
      location: [10, 10],
    },
    {
      asset_id: 6,
      name: "Sedan",
      description: "Altis",
      type: "Vehicle",
      serial: "Vehicle-6",
      assignee: "Jane Doe",
      tracker_no: "ABC103-400400-6",
      status: "ACTIVE",
      location: [10, 10],
    },
  ],
  assetTypes: ["Machine", "Vehicle", "Other"],
  assetStatuses: ["ACTIVE", "INACTIVE", "PENDING"],
  showAssetForm: false,
  assignees: [
    {
      assignee_id: 1,
      employee_id: "EMP-1",
      name: "John Doe",
      description: "Chief",
      status: "ACTIVE",
      location: [10, 10],
    },
    {
      assignee_id: 2,
      employee_id: "EMP-2",
      name: "Jane Doe",
      description: "Private",
      status: "INACTIVE",
      location: [10, 10],
    },
  ],
  assigneeStatuses: ["ACTIVE", "INACTIVE"],
  showAssigneeForm: false,
  locations: [],
};
